import { writeFile } from 'node:fs/promises';
import { BufferGeometry, Float32BufferAttribute, Mesh, MeshBasicMaterial, DoubleSide, Raycaster, Vector3 } from 'three';
import { collisionGeometry } from '../shared/physics';
import { TRACKS } from '../shared/tracks';

const config = await fetch('http://127.0.0.1:3001/api/dev-circuit-config').then(r => r.json());
// Measured from the painted grid where present; compact staggered rows elsewhere.
const spacing: Record<string, [number, number, number]> = {
  bugatti: [6, 10, 0], spa: [-7.5, 16, -.5], barcelona: [-6, 16, 0],
  hungaroring: [-6, 12, 0], indianapolis: [5, 10, 0], daytona: [-1, 14, 0], 'marina-bay': [6.3, 16, 0],
};
const grids: Record<string, unknown> = {};
for (const track of TRACKS) {
  const anchor = config.starts[track.id], { vertices, indices, surfaces } = await collisionGeometry(track);
  const points: number[][] = [[], [], []];
  surfaces.forEach((surface, triangle) => {
    const ids = Array.from(indices.subarray(triangle * 3, triangle * 3 + 3));
    if (!ids.some(i => Math.hypot(vertices[i * 3] - anchor.position.x, vertices[i * 3 + 2] - anchor.position.z) < 100)) return;
    for (const i of ids) points[surface].push(vertices[i * 3], vertices[i * 3 + 1], vertices[i * 3 + 2]);
  });
  const meshes = points.map((p, surface) => {
    const geometry = new BufferGeometry(); geometry.setAttribute('position', new Float32BufferAttribute(p, 3));
    const mesh = new Mesh(geometry, new MeshBasicMaterial({ side: DoubleSide })); mesh.userData.surface = surface; mesh.updateMatrixWorld(); return mesh;
  });
  const ray = new Raycaster(), forward = new Vector3(Math.sin(anchor.heading), 0, Math.cos(anchor.heading));
  const right = new Vector3(forward.z, 0, -forward.x);
  const ground = (x: number, z: number) => {
    ray.set(new Vector3(x, anchor.position.y + 8, z), new Vector3(0, -1, 0)); ray.far = 16;
    const hit = ray.intersectObjects(meshes, false)[0];
    return hit && hit.object.userData.surface === 0 && Math.abs(hit.face!.normal.y) > .85 ? hit.point.y : undefined;
  };
  const [lane, row, drift] = spacing[track.id];
  const slots = Array.from({ length: 8 }, (_, i) => {
    const back = Math.floor(i / 2) * row + (i % 2) * row / 2, side = (i % 2) * lane + Math.floor(i / 2) * drift;
    const p = new Vector3(anchor.position.x, anchor.position.y, anchor.position.z).addScaledVector(forward, -back).addScaledVector(right, side);
    const y = ground(p.x, p.z);
    if (y === undefined) throw new Error(`${track.id} slot ${i + 1}: no road at center`);
    for (let x = -1.25; x <= 1.251; x += .25) for (let z = -3.05; z <= 3.051; z += .305) {
      const q = p.clone().addScaledVector(right, x).addScaledVector(forward, z), height = ground(q.x, q.z);
      if (height === undefined || Math.abs(height - y) > .65) throw new Error(`${track.id} slot ${i + 1}: footprint off road (${x}, ${z})`);
    }
    return { position: { x: p.x, y, z: p.z }, heading: anchor.heading };
  });
  grids[track.id] = { anchor, slots };
  console.log(`${track.id}: 8 footprints on solid ground`);
  meshes.forEach(mesh => { mesh.geometry.dispose(); mesh.material.dispose(); });
}
await writeFile('shared/party-grids.ts', `// Generated by design/build-party-grids.ts; revalidate after moving a start.\nexport const PARTY_GRIDS = ${JSON.stringify(grids, null, 2)};\n`);
